# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExoscaleCli < Formula
  desc "Manage easily your Exoscale infrastructure from the command-line."
  homepage "https://exoscale.github.io/cli/"
  version "0.51.3"

  on_macos do
    url "https://github.com/exoscale/cli/releases/download/v0.51.3/exoscale-cli_0.51.3_darwin_all.tar.gz"
    sha256 "48866175582d97ff03325fe121a599b56127eaca60dd626b8c6dc5bd64d26214"

    def install
      bin.install "exoscale-cli" => "exo"
      man1.install Dir["manpage/exo*.1"]
      bash_completion.install "contrib/completion/bash/exo"
      zsh_completion.install "contrib/completion/zsh/_exo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v0.51.3/exoscale-cli_0.51.3_linux_armv6.tar.gz"
      sha256 "dd8f7d81cbd629278d8a4c7bbb71e8caf05a891ea6df4459afda1e571e61ba2b"

      def install
        bin.install "exoscale-cli" => "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/exoscale/cli/releases/download/v0.51.3/exoscale-cli_0.51.3_linux_amd64.tar.gz"
      sha256 "2e93a436cfaf8b55501041c8e3bfd0ad15a8ca797cb49baafadfae2143dabbed"

      def install
        bin.install "exoscale-cli" => "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/exoscale/cli/releases/download/v0.51.3/exoscale-cli_0.51.3_linux_arm64.tar.gz"
      sha256 "734e552540411973834efb524b0639db33a47d71f54d42805614fd3ffc56c95f"

      def install
        bin.install "exoscale-cli" => "exo"
        man1.install Dir["manpage/exo*.1"]
        bash_completion.install "contrib/completion/bash/exo"
        zsh_completion.install "contrib/completion/zsh/_exo"
      end
    end
  end
end
