# This file was generated by GoReleaser. DO NOT EDIT.
class ExoscaleCli < Formula
  desc "Manage easily your Exoscale infrastructure from the command-line."
  homepage "https://exoscale.github.io/cli/"
  version "1.20.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/exoscale/cli/releases/download/v1.20.0/exoscale-cli_1.20.0_darwin_amd64.tar.gz"
    sha256 "9d10a7c409f1baa4b7096550b9daec91c097d9b909430c6b2e4633d12b611542"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/exoscale/cli/releases/download/v1.20.0/exoscale-cli_1.20.0_linux_amd64.tar.gz"
      sha256 "d5179128b4a132bec432d615ca56c53877ba59b56680030aa46b62839e7ede53"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/exoscale/cli/releases/download/v1.20.0/exoscale-cli_1.20.0_linux_arm64.tar.gz"
        sha256 "333df5aac5a24f61bd3145f8e1202fa5510676a11f5bcf83f5ff97e73459b630"
      else
        url "https://github.com/exoscale/cli/releases/download/v1.20.0/exoscale-cli_1.20.0_linux_armv6.tar.gz"
        sha256 "429bedd38907aae00325ae1e79812940fe39e113100b16debccf73049b09ac24"
      end
    end
  end

  def install
    bin.install "exo"
    man1.install Dir["manpage/exo*.1"]
    bash_completion.install "contrib/completion/bash/exo"
  end
end
